---
  - import_tasks: "centos.yml"
    when:
      ansible_distribution == "CentOS"

  - import_tasks: "ubuntu.yml"
    when:
      ansible_distribution == "Ubuntu"

  - name: Register variable flask_imicrobe_dir
    stat:
      path: /home/imicrobe/flask-imicrobe
    register: flask_imicrobe_dir
    become_user: imicrobe

  - name: Clone the flask-imicrobe repository if it does not yet exist
    git:
      repo: https://github.com/hurwitzlab/flask-imicrobe.git
      dest: /home/imicrobe/flask-imicrobe
    when:
      flask_imicrobe_dir.stat.exists == false
    become_user: imicrobe

  # the output of 'git branch' will look something like this
  # if the develop branch has been checked out:
  #   * develop
  #     master
  #- name: Register variable flask_imicrobe_branch
  #  command: git branch
  #  register: flask_imicrobe_branch
  #  args:
  #    chdir: /home/imicrobe/flask-imicrobe
  #  become_user: imicrobe

  #- name: Checkout branch 'develop' if it has not been checked out
  #  command: git checkout develop
  #  args:
  #    chdir: /home/imicrobe/flask-imicrobe
  #  when:
  #    flask_imicrobe_branch.stdout.splitlines()[0].endswith('develop') == false
  #  become_user: imicrobe

  - name: Create a production virtual environment for flask-imicrobe
    command: "{{ item }}"
    with_items:
      - rm -rf flim
      - python3.6 -m venv flim
      - flim/bin/pip install setuptools --upgrade
      - flim/bin/pip install wheel
      # having trouble with this
      #- flim/bin/pip install -r requirements.txt
      #- flim/bin/python /home/imicrobe/flask-imicrobe/write_models.py
    args:
      chdir: /home/imicrobe/flask-imicrobe
    become_user: imicrobe
