---
  - name: Ubuntu | Install Python 3.6
    apt:
      name: "{{ item }}"
    with_items:
      - python3.6
      - python3.6-venv
      - python3.6-dev

  - name: Ubuntu | Install pip, setuptools, wheel (why no apt package?)
    shell: curl https://bootstrap.pypa.io/get-pip.py | python3.6

  - name: Ubuntu | Set IMICROBE_DB_URI for development as vagrant user
    lineinfile:
      path: /home/vagrant/.profile
      line: export IMICROBE_DB_URI=mysql+pymysql://imicrobe:{{ imicrobe_mysql_pw }}@127.0.0.1/imicrobe
    become: false

  - name: Ubuntu | Set IMICROBE_FLASK_CONFIG for development as vagrant user
    lineinfile:
      path: /home/vagrant/.profile
      line: export IMICROBE_FLASK_CONFIG=development
    become: false
