---
- name: Install iMicrobe on CentOS 7
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - imicrobe_vars_local.yml

  roles:
    - { role: imicrobe.update-yum-repos }

    - { role: ontic.nginx }
    - { role: CSC-IT-Center-for-Science.mariadb, 
        mariadb_state: latest,
        mariadb_root_password: "{{ root_mysql_pw }}",
        __mariadb_packages: [mariadb-server, mariadb-devel] }
    - { role: lesmyrmidons.mongodb, 
        mongodb_version: "3.4",
        mongodb_repo_baseurl: "https://repo.mongodb.org/yum/redhat/{{ ansible_distribution_major_version }}/mongodb-org/{{ mongodb_version }}/x86_64/",
        mongodb_repo_gpgcheck: yes,
        mongodb_repo_gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc" }

    - { role: imicrobe.account }
    - { role: imicrobe.mojolicious }

    - { role: imicrobe.imicrobe-lib }
    - { role: imicrobe.imicrobe-mojo }
    - { role: imicrobe.import-dbs }

    - { role: imicrobe.nginx }

  tasks:
    # the default wait_timeout and interactive_timeout are very high and we
    # run out of connections quickly because they stay open a long time after
    # the web app is done with them
    # crawling the site at 200 urls/minute uses up the connections if max_connections
    # is the default 150
    # I tried using with_items here but only the last item appeared in the file
    - name: configure MariaDB server connection wait_timeout and interactive_timeout
      blockinfile:
        path: /etc/my.cnf.d/server.cnf
        block: |
          wait_timeout=30
          interactive_timeout=30
          max_connections=1000
        insertafter: "^\\[mysqld\\]"

    - name: install htop
      package:
        name: htop
        state: latest
