---
  - name: CentOS | Install EPEL
    yum:
      name: epel-release
      enablerepo: extras
      state: latest

  - name: CentOS | Update system packages
    yum:
      name: "*"
      update_cache: yes
      state: latest

  - name: CentOS | Install basic packages and development tools
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - yum-utils
      - dkms
      - "@development"
      - zlib-devel
      - openssl-devel
      - htop

  - name: CentOS | Install fresh Perl to /usr/local/bin/perl
    shell: |
      cd /tmp
      wget http://www.cpan.org/src/5.0/perl-5.24.1.tar.gz
      tar -xzf perl-5.24.1.tar.gz
      cd perl-5.24.1
      ./Configure -des
      make
      make install

  - name: CentOS | Install cpanm
    shell: curl -L https://cpanmin.us | /usr/local/bin/perl - --sudo App::cpanminus

  - name: CentOS | Install Node.js 7.x + npm 4.x (npm 5.x is broken)
    shell: "{{ item }}"
    with_items:
      - "curl -sL https://rpm.nodesource.com/setup_7.x | sudo -E bash -"
      - "yum install -y nodejs"
      - "npm uninstall --save node-uuid"  # this module is deprecated and
      - "npm install --save uuid"         # causes other installs to fail

  - name: CentOS | Add MariaDB 10.1 yum repository but install later
    yum_repository:
      name: mariadb
      description: MariaDB 10.1 CentOS 7 repo
      file: mariadb
      baseurl: http://yum.mariadb.org/10.1/centos7-amd64
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: yes
