---
  - name: Ubuntu | Update the system
    command: "{{ item }}"
    with_items:
      - apt update
      - apt -y full-upgrade
    when:
      ansible_distribution == 'Ubuntu'

  - name: Ubuntu | Install basic packages and development tools
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - apt-utils
      - build-essential
      - libssl-dev
      - htop
    when:
      ansible_distribution == 'Ubuntu'

  - name: Ubuntu | Install cpanm
    shell: curl -L https://cpanmin.us | perl - --sudo App::cpanminus
    when:
      ansible_distribution == 'Ubuntu'

  - name: Ubuntu | Install node 7.x + npm 4.x (node 8.x + npm 5.x are broken)
    shell: "{{ item }}"
    with_items:
      - "curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -"
      - "apt-get install -y nodejs"
      #- "npm install -g n"
      #- "n latest"
      - "npm uninstall --save node-uuid"  # this module is deprecated and
      - "npm install --save uuid"         # causes other installs to fail
    when:
      ansible_distribution == 'Ubuntu'

  # 10.2 is not compatible with perl-DBD yet
  - name: Ubuntu | add MariaDB 10.1 apt repository key but install later
    command: "{{ item }}"
    with_items:
      - apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
      - add-apt-repository 'deb [arch=amd64] http://ftp.heanet.ie/mirrors/mariadb/repo/10.1/ubuntu yakkety main'
      - apt update
      # installing here hangs I don't know why
    when:
      ansible_distribution == 'Ubuntu'

  - name: CentOS | Install EPEL
    yum:
      name: epel-release
      enablerepo: extras
      state: latest
    when:
      ansible_distribution == 'CentOS'

  - name: CentOS | Update system packages
    yum:
      name: "*"
      update_cache: yes
      state: latest
    when:
      ansible_distribution == 'CentOS'

  - name: CentOS | Install basic packages and development tools
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - yum-utils
      - dkms
      - "@development"
      - zlib-devel
      - openssl-devel
      - htop
    when:
      ansible_distribution == 'CentOS'

  - name: CentOS | Install fresh Perl to /usr/local/bin/perl
    shell: |
      cd /tmp
      wget http://www.cpan.org/src/5.0/perl-5.24.1.tar.gz
      tar -xzf perl-5.24.1.tar.gz
      cd perl-5.24.1
      ./Configure -des
      make
      make install
    when:
      ansible_distribution == 'CentOS'

  - name: CentOS | Install cpanm
    shell: curl -L https://cpanmin.us | /usr/local/bin/perl - --sudo App::cpanminus
    when:
      ansible_distribution == 'CentOS'

  - name: CentOS | Install Node.js 7.x + npm 4.x (npm 5.x is broken)
    shell: "{{ item }}"
    with_items:
      - "curl -sL https://rpm.nodesource.com/setup_7.x | sudo -E bash -"
      - "yum install -y nodejs"
      #- "npm install -g n"
      #- "n latest"
      - "npm uninstall --save node-uuid"  # this module is deprecated and
      - "npm install --save uuid"         # causes other installs to fail
    when:
      ansible_distribution == 'CentOS'

  - name: CentOS | Add MariaDB 10.1 yum repository but install later
    yum_repository:
      name: mariadb
      description: MariaDB 10.1 CentOS 7 repo
      file: mariadb
      baseurl: http://yum.mariadb.org/10.1/centos7-amd64
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: yes
    when:
      ansible_distribution == 'CentOS'
