---
- name: install development tools
  yum:
    name: "@development-tools"
    state: latest

- name: install epel-release (must do this as a separate task)
  yum:
    name: epel-release
    state: latest

- name: install a bunch of stuff
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - nodejs
    - npm
    - git
    - ruby

- name: install node stuff
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - gulp-cli
    - gulp
    - bower

- name: get microsites code
  git:
    repo: https://bitbucket.org/agaveapi/microsites.git
    dest: /home/vagrant/microsites
    clone: yes
  become: yes
  become_user: vagrant

- name: replace implicit.js
  copy:
    src: files/microsites/implicit.js
    dest: /home/vagrant/microsites/web/app/js/implicit.js
  become: yes
  become_user: vagrant

- name: replace one line in main.js
  lineinfile:
    path: /home/vagrant/microsites/web/app/js/main.js
    regexp: "tenantId:"
    line: "tenantId: 'iplantc.org',"

- name: install microsites dependencies
  command: npm install
  args:
    chdir: /home/vagrant/microsites/web

- name: install microsites dependencies with bower
  command: bower install
  args:
    chdir: /home/vagrant/microsites/web
  become: yes
  become_user: vagrant
