---
- name: install MySQL-python for ansible
  package:
    name: MySQL-python
    state: latest

# grant all on `imicrobe`.* to `imicrobe`@localhost identified by '<password>';
- name: Create imicrobe database user
  mysql_user:
    name: imicrobe
    password: "{{ imicrobe_mysql_pw }}"
    priv: "*.*:ALL"
    state: present

- name: Copy imicrobe database dump to VM 
  get_url:
    url: ftp://ftp.imicrobe.us/database/imicrobe-2017-04-13.sql.gz
    dest: /tmp/

- name: Import imicrobe database
  mysql_db:
    name: imicrobe
    state: import
    target: /tmp/imicrobe-2017-04-13.sql.gz

- name: Start the mongod service (there is an Ansible handler for this but I need mongo running now)
  service:
    name: mongod
    state: started

- name: use 'localhost' for the mongo host
  lineinfile:
    path: /home/imicrobe/imicrobe/lib/conf/imicrobe.yaml
    regexp: "  host:"
    line: "  host: \"localhost\""

- name: Build the mongo database
  shell: IMICROBE_CONF=/home/imicrobe/imicrobe/lib/conf/imicrobe.yaml /home/imicrobe/perl5/perlbrew/perls/perl-5.25.10/bin/perl scripts/load-search.pl
  args:
    chdir: /home/imicrobe/imicrobe/lib
  become_user: imicrobe
