---
- name: Create imicrobe group
  group:
    name: imicrobe
    state: present

- name: Create imicrobe account
  user:
    name: imicrobe
    group: imicrobe

- name: Create /home/imicrobe/imicrobe
  file:
    path: /home/imicrobe/imicrobe
    state: directory
  become_user: imicrobe

- name: create ~/.my.conf
  template:
    src: ./templates/my.cnf.j2
    dest: /home/imicrobe/.my.cnf
    owner: imicrobe
    group: imicrobe
    mode: "u+rw,g-rwx,o-rwx"
