---
- name: install gcc required to build some Perl modules
  yum: name=gcc
       state=present

- name: install cpan and perl-devel
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - perl-devel
    - perl-CPAN

- name: download cpanm
  get_url: url=https://cpanmin.us/
           dest=/tmp/cpanm.pl
           mode=755

- name: install cpanm so that we can use the ansible cpanm module
  command: perl cpanm.pl App::cpanminus
  args:
    chdir: /tmp/
    creates: /usr/local/bin/cpanm

- name: add cpanm symbolic link to /usr/bin/
  file: src=/usr/local/bin/cpanm
        dest=/usr/bin/cpanm
        state=link

- name: download perlbrew
  get_url:
    url: https://install.perlbrew.pl
    dest: /tmp/install.perlbrew.pl

- name: install perlbrew
  command: bash /tmp/install.perlbrew.pl
  args:
    creates: /home/vagrant/perl5/perlbrew/bin/perlbrew
  become_user: vagrant

- name: install perl-5.25.10 using perlbrew
  command: /home/vagrant/perl5/perlbrew/bin/perlbrew install perl-5.25.10
  args:
    creates: /home/vagrant/perl5/perlbrew/perls/perl-5.25.10/bin/perl
  become_user: vagrant

- name: install Mojolicious using perl-5.25.10
  shell: "curl -L https://cpanmin.us | /home/vagrant/perl5/perlbrew/perls/perl-5.25.10/bin/perl - -M https://cpan.metacpan.org -n Mojolicious"
  become_user: vagrant

- name: install zlib-devel - needed for DBD::mysql
  yum:
    name: zlib-devel
    state: latest

- name: install openssl-devel - needed for DBD::mysql
  yum:
    name: openssl-devel
    state: latest

- name: install dependencies
  command: "/home/vagrant/perl5/perlbrew/perls/perl-5.25.10/bin/cpan {{ item }}"
  with_items:
    - DBIx::Class::Schema::Loader
    - namespace::autoclean
    - Moose::Util::TypeConstraints
    - YAML
    - MooseX::MarkAsMethods
    - MooseX::NonMoose
    - MongoDB
    - Readonly
    - DBD::mysql
  become_user: vagrant

- name: create ~/.my.conf
  template:
    src: ./templates/my.cnf.j2
    dest: /home/vagrant/.my.cnf
    owner: vagrant
    group: vagrant
    mode: "u+rw,g-rwx,o-rwx"

# to access mojolicious: ./perl5/perlbrew/bin/perlbrew use perl-5.25.10