---
- name: install gcc required to build some Perl modules
  yum: name=gcc
       state=present

- name: install perl, cpan, cpanminus (must use yum for cpanminus on system perl otherwise it does not work)
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - perl
    - perl-devel
    - perl-CPAN
    - cpanminus

- name: install zlib-devel - needed for DBD::mysql
  yum:
    name: zlib-devel
    state: latest

- name: install openssl-devel - needed for DBD::mysql
  yum:
    name: openssl-devel
    state: latest

- name: create ~/.my.conf
  template:
    src: ./templates/my.cnf.j2
    dest: /home/imicrobe/.my.cnf
    owner: imicrobe
    group: imicrobe
    mode: "u+rw,g-rwx,o-rwx"
