---
- name: install MySQL-python for ansible
  package:
    name: MySQL-python
    state: latest

- name: Create muscope database user
  mysql_user:
    name: muscope
    password: 
    priv: "*.*:ALL"
    state: present

- name: Create database 'muscope'
  mysql_db:
    name: muscope
    state: present
    login_user: root
    login_password: 

- name: Copy muscope_dump.sql to VM 
  copy:
    src: /Users/jlynch/project/imicrobe/exported-dbs/muscope_dump_20170329.sql
    dest: /tmp/muscope_dump.sql
    owner: vagrant
    group: vagrant

- name: Import muscope database
  mysql_db:
    name: muscope
    state: import
    target: /tmp/muscope_dump.sql

- name: Create database 'muscope_wordpress'
  mysql_db:
    name: muscope_wordpress
    state: present
    login_user: muscope
    login_password: muscope

- name: Copy muscope_wordpress_dump.sql to VM 
  copy:
    src: /Users/jlynch/project/imicrobe/exported-dbs/muscope_wordpress_dump_20170329.sql
    dest: /tmp/muscope_wordpress_dump.sql

- name: Import muscope_wordpress database
  mysql_db:
    name: muscope_wordpress
    state: import
    target: /tmp/muscope_wordpress_dump.sql

- name: copy and unpack muscope mongodb database dump to VM
  unarchive:
    src: /Users/jlynch/project/imicrobe/exported-dbs/muscope_mongo_dump_20170329.tar.gz
    dest: /tmp

- name: start the mongod service (why did the mongodb role not do this?)
  service:
    name: mongod
    state: started

- name: use mongorestore to load the mongodb database dump
  command: mongorestore /tmp/dump

- name: clean up
  command: rm -rf /tmp/dump
