---
- name: install git for ansible
  package:
    name: git
    state: latest

- name: install Node.js for variety
  package:
    name: nodejs
    state: latest

- name: install variety-cli for load-search.pl
  npm:
    name: variety-cli
    global: yes

- name: Create /usr/local/imicrobe
  file:
    path: /usr/local/imicrobe
    state: directory

- name: Create /home/imicrobe/imicrobe
  file:
    path: /home/imicrobe/imicrobe
    state: directory
  become_user: imicrobe

- name: Has the repository already been cloned?
  stat: path=/home/imicrobe/imicrobe/lib/.git
  register: imicrobe_lib_dot_git

- name: clone the imicrobe-lib repository
  git:
    repo: https://github.com/hurwitzlab/imicrobe-lib.git
    dest: /home/imicrobe/imicrobe/lib
  become_user: imicrobe
  when: not imicrobe_lib_dot_git.stat.exists

#- name: checkout the vm branch
#  command: git checkout vm
#  args:
#    chdir: /home/imicrobe/imicrobe/lib
#  become_user: imicrobe
