---
- name: Install variety-cli for load-search.pl
  npm:
     name: variety-cli
     global: yes
     executable: /usr/bin/npm

- name: Has the repository already been cloned?
  stat: path=/home/imicrobe/imicrobe/lib/.git
  register: imicrobe_lib_dot_git

- name: clone the imicrobe-lib repository
  git:
    repo: https://github.com/hurwitzlab/imicrobe-lib.git
    dest: /home/imicrobe/imicrobe/lib
  when: not imicrobe_lib_dot_git.stat.exists
  become_user: imicrobe

- name: checkout the newvm branch
  command: git checkout newvm
  args:
    chdir: /home/imicrobe/imicrobe/lib
  become_user: imicrobe
