---
- name: install git for ansible
  package:
    name: git
    state: latest

- name: clone the imicrobe-lib repository
  git:
    repo: https://github.com/hurwitzlab/imicrobe-lib.git
    dest: /home/vagrant/imicrobe-lib
