---
- name: install git for ansible
  package:
    name: git
    state: latest

- name: install Node.js for variety
  package:
    name: nodejs
    state: latest

- name: install variety-cli for load-search.pl
  npm:
    name: variety-cli
    global: yes

- name: Create /usr/local/imicrobe
  file:
    path: /usr/local/imicrobe
    state: directory

- name: Create /home/imicrobe/imicrobe
  file:
    path: /home/imicrobe/imicrobe
    state: directory
  become_user: imicrobe

- name: clone the imicrobe-lib repository
  git:
    repo: https://github.com/hurwitzlab/imicrobe-lib.git
    dest: /home/imicrobe/imicrobe/lib
    force: True
  become_user: imicrobe

- name: checkout the vm branch
  command: git checkout vm
  args:
    chdir: /home/imicrobe/imicrobe/lib
