---
- name: install git for ansible
  package:
    name: git
    state: latest

- name: Create /usr/local/imicrobe
  file:
    path: /usr/local/imicrobe
    state: directory

- name: Create /home/imicrobe/imicrobe
  file:
    path: /home/imicrobe/imicrobe
    state: directory
  become_user: imicrobe

- name: clone the imicrobe-lib repository
  git:
    repo: https://github.com/hurwitzlab/imicrobe-lib.git
    dest: /home/imicrobe/imicrobe/lib
    force: True
  become_user: imicrobe
