---
  - include: "centos.yml"
    when:
      ansible_distribution == "CentOS"

  - include: "ubuntu.yml"
    when:
      ansible_distribution == "Ubuntu"

  - name: Create the /etc/ssl/self-signed directory
    file:
      path: /etc/ssl/self-signed
      state: directory

  - name: Create a self-signed certificate
    command: openssl req -newkey rsa:2048 -nodes -keyout /etc/ssl/self-signed/data-imicrobe-us.key -x509 -days 365 -out /etc/ssl/self-signed/data-imicrobe-us.crt -subj "/C=US/ST=Arizona/L=Tucson/O=iMicrobe/CN=localhost"
