---
  - name: Ubuntu | Install nginx
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - nginx
      - certbot
    when:
      ansible_distribution == 'Ubuntu'

  - name: Ubuntu | Configure the firewall
    command: "ufw allow 'Nginx Full'"
    when:
      ansible_distribution == 'Ubuntu'

  #- stat: path=/etc/nginx/conf.d/imicrobe.conf
  #  register: imicrobe_conf

  #- name: Configure nginx with imicrobe.conf
  #  copy:
  #    src: files/imicrobe.conf
  #    dest: /etc/nginx/conf.d/
  #  when: imicrobe_conf.stat.exists == False

  - stat: path=/etc/nginx/conf.d/imicrobe-node.conf
    register: imicrobe_node_conf

  - name: Configure nginx with imicrobe-node.conf
    copy:
      src: files/imicrobe-node.conf
      dest: /etc/nginx/conf.d/
    when: imicrobe_node_conf.stat.exists == False

  - name: Create the /etc/ssl/self-signed directory
    file:
      path: /etc/ssl/self-signed
      state: directory

  - name: Create a self-signed certificate
    command: openssl req -newkey rsa:2048 -nodes -keyout /etc/ssl/self-signed/data-imicrobe-us.key -x509 -days 365 -out /etc/ssl/self-signed/data-imicrobe-us.crt -subj "/C=US/ST=Arizona/L=Tucson/O=iMicrobe/CN=localhost"

  # TODO remove this?
  #- name: Remove default nginx configuration
  #  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.bak
  #  when: imicrobe_conf.stat.exists == False
