---
- name: install git for ansible
  package:
    name: git
    state: latest

- name: Create /usr/local/imicrobe
  file:
    path: /usr/local/imicrobe
    state: directory

- name: Create /home/imicrobe/imicrobe
  file:
    path: /home/imicrobe/imicrobe
    state: directory
  become_user: imicrobe

- name: clone the imicrobe-mojo repository
  git:
    repo: https://github.com/hurwitzlab/imicrobe-mojo.git
    dest: /home/imicrobe/imicrobe/lib/mojo
    force: True
  become_user: imicrobe

- name: install dependencies from cpanfile
  command: "cpanm ."
  args:
    chdir: /home/imicrobe/imicrobe/lib/mojo
#  become_user: imicrobe

#- name: install dependencies
#  command: "/home/imicrobe/perl5/perlbrew/perls/perl-5.25.10/bin/cpan {{ item }}"
#  with_items:
#    - namespace::autoclean
#    - YAML
#    - MongoDB
#    - Readonly
#    - DBD::mysql
#    - JSON::XS
#    - LWP::UserAgent
#    - String::Trim
#    - DBIx::Class::Schema::Loader
#    - Moose::Util::TypeConstraints
#    - MooseX::MarkAsMethods
#    - MooseX::NonMoose
#    - Mojolicious::Plugin::TtRenderer
#  become_user: imicrobe

- name: copy mojolicious startup script to the imicrobe home directory
  copy:
    src: files/start_imicrobe_mojo.sh
    dest: /home/imicrobe/
    mode: u+x
  become_user: imicrobe

- name: copy mojolicious stop script to the imicrobe home directory
  copy:
    src: files/stop_imicrobe_mojo.sh
    dest: /home/imicrobe/
    mode: u+x
  become_user: imicrobe

- name: install imicrobe.service
  copy:
    src: files/imicrobe.service
    dest: /lib/systemd/system/

- name: start the imicrobe service
  service:
    name: imicrobe
    state: started
    enabled: yes
